"""Registry of the interactive tools embedded in topic pages.

A tool is two files, both optional to the build only in the sense that a missing
one is an error:

    static/js/tools/<name>.js     an IIFE that self initialises
    static/css/tools/<name>.css   styles, all selectors under .tool[data-tool=...]

Every tool is mounted by the `!tool <name>` markup directive, which writes

    <div class="tool" data-tool="<name>">
      <div class="tool-head">...</div>
      <div class="tool-body"><p class="tool-fallback">...</p></div>
    </div>

The script finds its own mounts with document.querySelectorAll and replaces the
contents of .tool-body. Because the fallback paragraph is rendered server side,
a reader without JavaScript sees an explanation rather than an empty box.

All tool files are concatenated into one bundle at build time, and `layout()`
only links that bundle on pages that actually mount a tool.
"""
import os

TOOLS = {
    "base-converter": {
        "title": "Number base converter",
        "icon": "i-binary",
        "blurb": "Convert between denary, binary and hexadecimal, with every step of "
                 "the working written out.",
        "long": "Type a number in any base and watch the other two update. Switch to "
                "practice mode for endless auto marked conversion questions with the "
                "method shown after each answer.",
    },
    "file-size": {
        "title": "File size calculator",
        "icon": "i-disk",
        "blurb": "Work out the size of an image, a sound file or a block of text, one "
                 "conversion at a time.",
        "long": "Choose image, sound or text, set the properties, and the calculator "
                "shows the formula, the substitution and every division from bits to "
                "bytes to kilobytes to megabytes.",
    },
    "logic-simulator": {
        "title": "Logic gate simulator",
        "icon": "i-gate",
        "blurb": "Build a circuit from gates, wire it up, and see the truth table fill "
                 "in as you go.",
        "long": "Place AND, OR, NOT, XOR, NAND and NOR gates on the canvas, drag from an "
                "output to an input to wire them, flip the inputs, and read the full "
                "truth table and Boolean expression the circuit produces.",
    },
    "sort-visualiser": {
        "title": "Sorting algorithm visualiser",
        "icon": "i-shuffle",
        "blurb": "Run bubble, insertion, merge and quick sort side by side and count "
                 "the comparisons.",
        "long": "Watch four sorting algorithms work on the same list at the same time, "
                "with a live count of comparisons and swaps, so the difference between "
                "them stops being an abstract claim.",
    },
    "trace-table": {
        "title": "Trace table trainer",
        "icon": "i-table",
        "blurb": "Fill in a trace table row by row and have it marked as you type.",
        "long": "Read the algorithm, fill in what each variable holds after each line, "
                "and every cell is checked the moment you leave it. Step through the "
                "answer afterwards to see exactly where a value changed.",
    },
    "lmc": {
        "title": "Little Man Computer",
        "icon": "i-cpu",
        "blurb": "Assemble and run LMC programs and watch the fetch decode execute cycle "
                 "happen.",
        "long": "Write LMC assembly, assemble it into the mailboxes, then run it or step "
                "one instruction at a time while the program counter, accumulator and "
                "each mailbox update in front of you.",
    },
}

# The order tools appear in on the /tools/ hub page.
ORDER = ["base-converter", "file-size", "logic-simulator", "sort-visualiser",
         "trace-table", "lmc"]


def _read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def bundle(root, kind):
    """Concatenate every tool's js or css into one file's worth of text."""
    ext = "js" if kind == "js" else "css"
    base = os.path.join(root, "static", ext, "tools")
    parts = ["/* MskProd interactive tools bundle. Generated by build.py. */"]
    for name in ORDER:
        p = os.path.join(base, name + "." + ext)
        if not os.path.exists(p):
            raise FileNotFoundError("missing tool asset: %s" % p)
        parts.append("/* ---- %s ---- */" % name)
        parts.append(_read(p).strip())
    return "\n".join(parts) + "\n"
